M48
; DRILL file {KiCad 9.0.5} date 2025-11-16T18:57:08+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-16T18:57:08+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X123.952Y-70.104
X123.998Y-153.416
X176.174Y-70.104
X176.22Y-153.416
M30
